# Generated by Django 3.2.4 on 2021-06-25 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
