# Generated by Django 3.2.4 on 2021-06-25 13:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
