# Generated by Django 3.2.4 on 2021-06-23 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ดาต้า', 'ดาต้า'), ('ลิ้งค์', 'ลิงค์'), ('ดาวเทียม', 'ดาวเทียม'), ('วงรอบ', 'วงรอบ'), ('เอกสาร', 'เอกสาร'), ('อื่น ๆ', 'อื่น ๆ')], default='อื่น ๆ', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
